# Generated by Django 3.2 on 2021-04-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
